version: '3'

services:
  php:
#    image: php:7.4-fpm-alpine
    build:
      context: .
      dockerfile: php.dockerfile
    working_dir: /var/www/html
    container_name: php
    restart: always
    volumes:
      - ./wordpress:/var/www/html:delegated
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:delegated
  pg:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: wp
      POSTGRES_DB: wp

#  mysql:
#    image: mysql:latest
#    environment:
#      MYSQL_DATABASE: wp
#      MYSQL_USER: wp
#      MYSQL_PASSWORD: secret
#      MYSQL_ROOT_PASSWORD: secret